export const BACKEND_API_BASE_URL = "http://localhost:3000"; // On Development change this to server IP
export const BACKEND_API_REST_VERSION = "v1";
export const BACKEND_API_IO_VERSION = "v1";
export const MAX_DOWNLOAD_ID_LENGTH = 50;
export const ON_OFF_THRESHOLD_MS = 6000;
export const ON_OFF_THRESHOLD_ERROR_MS = 4000;
export const FETCH_REST_TIME_MS = 10000;
export const IOT_INTERVAL_MS = 2000;
export const SUMMARY_GRAPH_PRECISION = 2;
export const ENVIRONMENT_STATUS = "PRODUCTION"; // On Development change this to "DEVELOPMENT"
export const PROGRESS_SCALING_FACTOR = 2000;
export const USAGE_NOTIFICATION_PAGING_LIMIT = 5;
export const MAX_NOTIFICATIONS_COUNT = 8;
